Security #1: Attempt to bump up `generic-array`
atsams-rs/atsamx7x-rust pull request #22
Opened 2022-07-24 16:24 UTC by michalfita

Addresses report from dependabot: https://github.com/atsams-rs/atsamx7x-rust/security/dependabot/1

2022-07-25 13:26 UTC, tmplt commented
The linked report does not exist: 404.

2022-07-25 13:30 UTC, michalfita commented
![image](https://user-images.githubusercontent.com/4925040/180789083-5d2f24c2-78a1-4cf8-a618-a4413b7f6654.png)
That's pretty interesting, so for some bizarre reason you don't have access rights to it.

2022-07-25 13:32 UTC, michalfita commented
What about now?

2022-07-25 13:42 UTC, tmplt requested changes
Still can't access the report. But both dep bumps LGTM. I'd rewrite the commit:

```
cargo: bump nb, cortex-m

nb bumped due to <link to report>.
```

or similar.

2022-07-25 13:42 UTC, tmplt commented on hal/Cargo.toml
> +version = "0.2.0"
Techically, a MINOR bump is overkill. A PATCH bump suffices.

2022-07-25 13:42 UTC, tmplt commented on hal/Cargo.toml
> +cortex-m = "0.7.5"
Commit does not mention a `cortex-m` bump.

2022-07-27 18:15 UTC, tmplt approved these changes

2022-07-27 21:46 UTC, merged