[Fixes #40] Adjust stuff for CI
atsams-rs/atsamx7x-rust pull request #41
Opened 2022-10-16 13:52 UTC by michalfita

Preparing stuff for HAL 0.4.0 release.

2022-10-16 14:38 UTC, tmplt requested changes

2022-10-16 14:38 UTC, tmplt commented on CHANGELOG.md
> +- Cargo Workspace sorted, so local builds and crate publictions work, and CI is satisfied.
GitHub CI was added with in this release, so there is no need to mention that a fix was applied.

2022-10-17 06:57 UTC, martinmortsell approved these changes
Looks good to me.

2022-10-18 15:12 UTC, tmplt requested changes

2022-10-18 15:12 UTC, tmplt commented on CHANGELOG.md
> +- Cargo Workspace sorted, so local builds and crate publictions work.
spelling

2022-10-18 15:12 UTC, tmplt commented on tools/update-pacs.sh
> +    #sed -e "s|\${crate}|${crate}|g" -e "s|\${chip}|${chip}|g" -e "s|\${pac}|${pac}|g" -e "s|\${version}|${version}|g" "${top}/pac/templates/README.md.template" > README.md
remove outcommented code

2022-10-19 13:58 UTC, tmplt approved these changes

2022-10-19 14:52 UTC, michalfita commented
[0.4.0 Released](https://github.com/atsams-rs/atsamx7x-rust/releases/tag/v0.4.0)!

2022-10-19 14:52 UTC, merged